#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/noble
- name: Create Noble directory
  file:
    path: "{{ noble_home_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Set up Dockerfile
  template:
    src: templates/Dockerfile.j2
    dest: "{{ noble_home_dir }}/Dockerfile"

- name: Set up start-noble.sh
  template:
    src: templates/start-noble.sh.j2
    dest: "{{ noble_home_dir }}/start-noble.sh"

- name: Build Noble Docker image
  docker_image:
    name: "{{ noble_image_name }}"
    source: build
    build:
      path: "{{ noble_home_dir }}"
    force_source: yes
  become: true

- name: Run Noble container
  docker_container:
    name: "{{ noble_container_name }}"
    image: "{{ noble_image_name }}"
    state: started
    recreate: yes
    volumes:
      - "{{ noble_home_dir }}:/root/.noble"
    env:
      MONIKER: "{{ noble_moniker }}"
      SNAPSHOT_URL: "{{ noble_snapshot_url }}"
    network_mode: host  
    restart_policy: unless-stopped
  become: true

