---
# tasks file for ansible/noble

- name: Stop noble container before fresh sync
  community.docker.docker_container:
    name: "{{ noble_container_name }}"
    state: stopped
  when: noble_fresh_sync | bool
  become: true

- name: Clear Noble data directories for fresh sync
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ noble_home_dir }}"
    - "{{ noble_data_dir }}"
    - "{{ noble_config_dir }}"
    - "{{ noble_container_data_dir }}"
  when: noble_fresh_sync | bool
  become: true

- name: Create Noble directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ noble_home_dir }}"
    - "{{ noble_data_dir }}"
    - "{{ noble_config_dir }}"
    - "{{ noble_container_data_dir }}"

- name: Modify permissions to match user-group inside docker image
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ noble_user }}"
    group: "{{ noble_group }}"
    recurse: true
    mode: "0700"
  with_items:
    - "{{ noble_home_dir }}"
    - "{{ noble_data_dir }}"
    - "{{ noble_config_dir }}"
    - "{{ noble_container_data_dir }}"

- name: Set up Dockerfile
  template:
    src: "Dockerfile.j2"
    dest: "{{ noble_home_dir }}/Dockerfile"
  notify:
    - Build Noble Docker image  

- name: Set up start-noble.sh
  template:
    src: "configure-noble.sh.j2"
    dest: "{{ noble_home_dir }}/configure-noble.sh"
  notify:
    - Build Noble Docker image

- name: Set up config.toml
  template:
    src: "config.toml.j2"
    dest: "{{ noble_config_dir }}/config.toml"
  notify:
    - Restart Noble container

- name: set up client.toml
  template:
    src: "client.toml.j2"
    dest: "{{ noble_config_dir }}/client.toml"
  notify:
    - Restart Noble container

- name: set up app.toml
  template:
    src: "app.toml.j2"
    dest: "{{ noble_config_dir }}/app.toml"
  notify:
    - Restart Noble container  

