---
- name: Set-up horcrux
  hosts: horcrux
  become: true
  gather_facts: true
  vars:
    priv_validator_key_src: ../validator_key/priv_validator_key.json
    noble_full_node: "{{ hostvars['noble-node'].ansible_host }}"
    horcrux_fresh_sync: true
  roles:
    - "../roles/horcrux"
