#SPDX-License-Identifier: MIT-0
---
- name: Stop Horcrux container before fresh sync
  community.docker.docker_container:
    name: "{{ horcrux_container_name }}"
    state: stopped
  when: horcrux_fresh_sync | bool
  become: true

- name: Clear Horcrux data directories for fresh sync
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ horcrux_signer_dir }}"
    - "{{ horcrux_signer_dir }}/horcrux"
    - "{{ horcrux_signer_dir }}/horcrux/state"
  when: horcrux_fresh_sync | bool
  become: true

- name: Ensure horcrux_signer_dir exists
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ horcrux_signer_dir }}"
    - "{{ horcrux_signer_dir }}/horcrux"
    - "{{ horcrux_signer_dir }}/horcrux/state"

- name: Copy priv_validator_key.json for Horcrux
  copy:
    src: "{{ priv_validator_key_src }}"
    dest: "{{ horcrux_signer_dir }}/horcrux/grand-1_priv_validator_key.json"
    mode: "0600"
    remote_src: no 
  when: priv_validator_key_src is defined

- name: Template the Dockerfile
  template:
    src: "Dockerfile.j2"
    dest: "{{ horcrux_signer_dir }}/Dockerfile"
    mode: '0644'
  notify:
    - Build Horcrux Docker image

- name: Template the horcrux config file
  template:
    src: "config.yaml.j2"
    dest: "{{ horcrux_signer_dir }}/horcrux/config.yaml"
    mode: '0644'
  notify:
    - Restart Horcrux container

